apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata: 
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "050298/hello-go:v6.3"

          resources:
            requests: #minimo que minha aplicação precisa; reservando do cluster para o pod
              cpu: 100m
              memory: 20Mi
            #até onde esse pod pode utilizar de recursos em nosso cluster
            limits:
            #evitar que a soma de todos os limites atinga o limite do meu cluster
              cpu: 500m
              memory: 25Mi
          #Verificar se a aplicação foi iniciada corretamente.
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            # Se ocorrerem 30 falhas consecutivas, com tentativas a cada 3 segundos, o container será reiniciado.
            periodSeconds: 3
            failureThreshold: 30
          #Verificar se o container está pronto para receber tráfego.
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10
          #Verificar se o container está em execução (vivo) e operando corretamente.
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"