apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 4
  selector: 
      matchLabels:
        app: mysql
  serviceName: mysql-h
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: myapp
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root 
